apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
  namespace: microservices
spec:
  replicas: 2
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: kennethfeh/service1:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4001
          env:
            - name: SERVICE1_MESSAGE
              value: "Service1 in Kubernetes"
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4001
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4001
            initialDelaySeconds: 15
            periodSeconds: 20
